# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160502_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='relationship_status',
            field=models.CharField(choices=[('MR', 'Married'), ('SN', 'Single'), ('RL', 'In a Relationship'), ('DV', 'Divorced')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='type',
            field=models.CharField(choices=[('FR', 'Friends'), ('AQ', 'Acquaintances')], max_length=2),
        ),
    ]
